config/routes.rb
Rails.application.routes.draw do
  devise_for :users, skip: [:session, :registration],
              controllers: { omniauth_callbacks: "omniauth_callbacks" }

  devise_for :users, controllers: {omniauth_callbacks: "omniauth_callbacks",
                                  passwords: "passwords",
                                  sessions: "sessions",
                                  confirmations: "confirmations",
                                  registrations: "registrations"}, skip: [:omniauth_callbacks]
  devise_scope :user do
    get "sign_out", to: "devise/sessions#destroy"
  end
    namespace :admin do
    root "static_pages#dashboard"
    get "about"=> "static_pages#about"
    get "edit_about"=> "static_pages#edit_about"
    patch "update_about"=> "static_pages#update_about"
    resources :videos
    resources :tags
    resources :articles
    resources :users
    resources :activities, only: [:index]
    resources :comments, only: [:show, :index, :destroy]
  end
  resources :tags, only: [:show]
  resources :users, only: [:show] do
    resources :activities, only: :index
    member do
      get "question"
      get "comment"
    end
  end
  resources :searchs, only: [:index]
  resources :articles, only: [:show, :index] do
    resources :comments
  end
  resources :videos, only: [:show, :index] do
    resources :comments
  end
  root "static_pages#home"
  get "about" => "static_pages#about"
  get "privacy" => "static_pages#privacy"

  # get "*path", to: redirect("/#{I18n.default_locale}/%{path}")
  # get "", to: redirect("/#{I18n.default_locale}/")
  match "errors/500", to: "errors#500", via: :all
  match "errors/404", to: "errors#404", via: :all
  match "errors/422", to: "errors#422", via: :all
  match "(errors)/:status", to: "errors#show", constraints: {status: /\d{3}/}, via: :all

  get "*path", to: redirect("/kh/%{path}"),
    constraints: lambda {|req| !req.path.starts_with?("/kh/") && !req.path.starts_with?("/en/")}
  get "", to: redirect("/kh/")
end

app/models/article.rb
class Article < ActiveRecord::Base
  extend FriendlyId
  # enum status: [:show, :hide]
  before_save :default_values
  has_many :comments, as: :commentable, dependent: :destroy
  belongs_to :user
  has_many :article_tags, dependent: :destroy
  has_many :tags, through: :article_tags

  validates :title, :content, presence: true

  friendly_id :title, use: :slugged

  scope :order_article, ->{
    order("created_at DESC")
  }

  def self.status_show
    where status: true
  end

  def simlar_articles
    if tags.any?
      tags.order("RAND()").first.articles.order("RAND()").limit(4)
    else
      Article.order("RAND()").limit(4)
    end
  end

  def default_values
    self.status ||= :show
    self.publish_date ||= Date.current
  end
end

app/controllers/admin/articles_controller.rb
class Admin::ArticlesController < ApplicationController
  before_action :authenticate_user!
  before_action :admin_user
  before_action :load_article, only: [:show, :edit, :update]
  layout "admin/application"

  def show
  end

  def index
    @articles = Article.order(publish_date: :desc).paginate page: params[:page], per_page: 7
  end

  def new
    @article = current_user.articles.new
  end

  def create
    @article = current_user.articles.new article_params
    if @article.save
      track_activity @article
      flash[:success] = t "flash.success_create"
      redirect_to [:admin, @article]
    else
      flash.now[:danger] = t "flash.fail_create"
      render "new"
    end
  end

  def edit
  end

  def update
    if @article.update_attributes article_params
      track_activity @article
      flash[:success] = t "flash.success_update"
      redirect_to [:admin, @article]
    else
      flash.now[:danger] = t "flash.fail_update"
      render "edit"
    end
  end

  def destroy
    @article = Article.friendly.find params[:id]
    @article.destroy
    track_activity @article
    flash[:success] = t "flash.success_delete"
    redirect_to admin_articles_path
  end

  private
  def article_params
    params.require(:article).permit :id, :content, :title, :description, :status,
                                    :publish_date, tag_ids:[]
  end

  def load_article
    @article = Article.includes(:user)
                      .friendly.find params[:id]
  end

  def admin_user
    redirect_to root_url unless current_user.admin? || current_user.super?
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  def show
    @article = Article.status_show.friendly.find params[:id]
    # @article.show?
    @simlar_articles = @article.simlar_articles
    @commentable = @article
    @comments = @commentable.comments
    @comment = Comment.new
  end

  def index
    @articles = Article.status_show.order(publish_date: :desc).paginate page: params[:page], per_page: 7
  end
end

app/views/articles/_article.html.erb
<!-- <div class="row"> -->
  <div class="col-md-12 article-show">
    <h3><%= link_to article.title, article %></h3>
    <p>
      <span class="text-muted small">
        <em>
          <%= t("label.post_by") %> <%= (link_to article.user.name, article.user) if article.user %>
          <br/>
          <%= l article.publish_date.localtime.to_date %>, <%= article.comments.size %> <%= t("articles.label.comment") %>
        </em>
      </span>
    </p>
    <p>
    <p class="acticle-info">
      <span class="text-muted small">
        <em>
          <%= t("articles.label.tag") %>
          <% article.tags.each do |tag| %>
            <%= link_to tag.name, tag %>
          <% end %>
        </em>
      </span>
    </p>    
      <p><%= article.description %></p>
      <%= link_to t("link.read_more"), article_path(article) %> 
    </p>
  </div>
<!-- </div> -->

app/views/articles/index.html.erb
<% if params[:search].present? %>
  <% provide :title, "#{t("page_title.search_article")} " + params[:search].to_s %>
  <b><%= t("search.label.filter") %> <%= params[:search] %></b>
  <% unless @articles && @articles.any? %>
    <p><%= t("search.label.video_no_found") %>  <%= link_to t("search.link.all_video"), articles_path %></p>
  <% else %>    
    <%= render @articles %>
    <%= will_paginate @articles %>
  <% end %>
<% else %>
  <% provide :title, t("page_title.article") %>
  <%= render @articles %>
  <%= will_paginate @articles %>
<% end %>

app/views/articles/show.html.erb
<% provide :title, @article.title %>
<div class="row">
  <div class="col-md-12 white-container question-detail">
    <h3 class="center"><%= @article.title.capitalize %></h3>
    <div class="style-markdown">
      <%= markdown @article.content %>
    </div>
    <hr/>
    <span class="text-muted small">
      <em>
        <%= t("label.post_by") %> <%= (link_to @article.user.name, @article.user) if @article.user %>
        <br/>
        <%= l @article.publish_date.localtime.to_date %>
        <br/>
        <p><%= t("articles.label.tag") %>
          <% @article.tags.each do |tag| %>
            <%= link_to tag.name, tag %>
          <% end %>
        </p>
      </em>
    </span>
    <%= social_share_button_tag(@article.title, :popup => "true", desc: @article.description) %>
  </div>
  <div class="col-md-12 white-container question-detail">
    <br/>
    <%= render "comments/comments" %>
    <% if user_signed_in? %>
      <div id="reply_comment_form">
        <%= render "comments/form", comment_title: t("comments.label.leave_comment") %>  
      </div>
    <% else %>
        <%= link_to t("devise.link.sign_in"), new_user_session_path  %>
        <%= t("comments.label.to_post") %>
    <% end %>
  </div>
  <div class="col-md-12">
    <div class="row well question-detail">
    <%= t("articles.label.similar_article") %>
    <ul>
    <% @simlar_articles.each do |article| %>
      <li>
        <%= link_to article do %>          
          <p><%= article.title %></p>
        <% end %>
      </li>            
    <% end %>
    </ul>
    </div>
  </div>
</div>
<script src="https://google-code-prettify.googlecode.com/svn/loader/run_prettify.js"></script>