config/routes.rb
Rails.application.routes.draw do
  devise_for :users, skip: [:session, :registration],
              controllers: { omniauth_callbacks: "omniauth_callbacks" }

  devise_for :users, controllers: {omniauth_callbacks: "omniauth_callbacks",
                                  passwords: "passwords",
                                  sessions: "sessions",
                                  confirmations: "confirmations",
                                  registrations: "registrations"}, skip: [:omniauth_callbacks]
  devise_scope :user do
    get "sign_out", to: "devise/sessions#destroy"
  end
    namespace :admin do
    root "static_pages#dashboard"
    get "about"=> "static_pages#about"
    get "edit_about"=> "static_pages#edit_about"
    patch "update_about"=> "static_pages#update_about"
    resources :videos
    resources :tags
    resources :articles
    resources :users
    resources :activities, only: [:index]
    resources :comments, only: [:show, :index, :destroy]
  end
  resources :tags, only: [:show]
  resources :users, only: [:show] do
    resources :activities, only: :index
    member do
      get "question"
      get "comment"
    end
  end
  resources :searchs, only: [:index]
  resources :articles, only: [:show, :index] do
    resources :comments
  end
  resources :videos, only: [:show, :index] do
    resources :comments
  end
  root "static_pages#home"
  get "about" => "static_pages#about"
  get "privacy" => "static_pages#privacy"

  # get "*path", to: redirect("/#{I18n.default_locale}/%{path}")
  # get "", to: redirect("/#{I18n.default_locale}/")
  match "errors/500", to: "errors#500", via: :all
  match "errors/404", to: "errors#404", via: :all
  match "errors/422", to: "errors#422", via: :all
  match "(errors)/:status", to: "errors#show", constraints: {status: /\d{3}/}, via: :all

  get "*path", to: redirect("/kh/%{path}"),
    constraints: lambda {|req| !req.path.starts_with?("/kh/") && !req.path.starts_with?("/en/")}
  get "", to: redirect("/kh/")
end

app/views/layouts/admin/_header.html.erb
<header>
  <div class="navbar navbar-inverse navbar-fixed-top">
    <div class="container-fluid">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#collape-side-bar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </button>
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#collape-user">
            <span class="sr-only">Toggle navigation</span>
            <i class="fa fa-user"></i>
        </button>
        <%= link_to admin_root_path do %>
          <span class="navbar-brand"><%= t("layouts.admin.header.link.root_path") %></span>
        <% end %>
      </div>
      <div class="collapse navbar-collapse" id="collape-user">
        <ul class="nav navbar-right user-nav">
          <li class="pull-right">
            <%= link_to t("layouts.admin.header.link.welcome") + "#{current_user.name}", "#", class:"dropdown-toggle", id:"admin-user-header",
                      'aria-expanded' =>'false', data: {toggle: "dropdown"} %>
              <ul id="login-dp" class="dropdown-menu">
                <li>
                  <%= link_to [:admin, current_user] do%>
                    <i class="fa fa-user"> </i>  <%= t("layouts.admin.header.link.profile") %>
                  <%end%>
                </li>
                <li class="divider"></li>
                <li><%= link_to sign_out_path do%>
                  <span class="center"><i class="fa fa-sign-out fa-lg"></i>  <%= t("layouts.admin.header.link.sign_out") %></span>
                <%end%>
                </li>
                <br/>
              </ul>
          </li>
        </ul>
      </div>
      <div class="collapse navbar-collapse" id="collape-side-bar">
          <ul class="nav navbar-nav side-nav">
              <li class="<%= "active" if controller?("admin/static_pages")&& action?("dashboard") %> %>">
                <%= link_to admin_root_path do %>
                  <i class="fa fa-fw fa-dashboard"></i> <%= t("layouts.admin.header.link.dashboard") %>
                <% end %>
              </li>
              <li class="<%= "active" if controller?("admin/tags") %>">
                <%= link_to admin_tags_path do %>
                  <i class="fa fa-tags"></i> <%= t("layouts.admin.header.link.tag") %>
                <% end %>
              </li>
              <li class="<%= "active" if controller?("admin/articles") %>">
                <%= link_to admin_articles_path do %>
                  <i class="fa fa-book"></i> <%= t("layouts.admin.header.link.articles") %>
                <% end %>
              </li>
              <li class="<%= "active" if controller?("admin/videos") %>">
                <%= link_to admin_videos_path do %>
                  <i class="fa fa-video-camera"></i> <%= t("layouts.admin.header.link.videos") %>
                <% end %>
              </li>
              <li class="<%= "active" if controller?("admin/users") %>">
                <%= link_to admin_users_path do %>
                  <i class="fa fa-user"></i> <%= t("layouts.admin.header.link.users") %>
                <% end %>
              </li>
              <li class="<%= "active" if controller?("admin/comments") %>">
                <%= link_to admin_comments_path do %>
                  <i class="fa fa-comment"></i> <%= t("layouts.admin.header.link.comments") %>
                <% end %>
              </li>
              <li class="<%= "active" if controller?("admin/activities") %>">
                <%= link_to admin_activities_path do %>
                  <i class="fa fa-eye"></i> <%= t("layouts.admin.header.link.activities") %>
                <% end %>
              </li>
              <li class="<%= "active" if controller?("admin/static_pages") && !action?("dashboard") %>" >
                <%= link_to admin_about_path do %>
                  <i class="fa fa-info-circle"></i> <%= t("layouts.admin.header.link.about") %>
                <% end %>
              </li>
              <li>
                <%= link_to root_path do %>
                  <i class="fa fa-arrow-right"></i> <%= t("layouts.admin.header.link.home_page") %>
                <% end %>
              </li>
          </ul>
      </div>
      <!-- /.navbar-collapse -->
    </div>
  </div>
</header>

app/views/layouts/admin/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="description" content="អត្ថបទ​ វីដេអូ និងសំនួរដែលនិយាយអំពីភាសារកុំព្យូទ័រមានដូចជា គន្លឹះ ល្បិច និង ការបង្រៀន។ ល្អសម្រាប់អ្នកមិនទាន់ចេះឫអ្នកចេះខ្លះៗហើយនៅលើផ្នែក game, mobile, PC ហើយនិង web។" />
    <meta name="keywords" content="C, C++, Java, Ruby, javascript, jQuery, css, html, ruby on rails, android, ios, screencasts, articles, tips, tricks, tutorials, training, podcasts, programming, game, PC , web, mobile, computer language, អត្ថបទ​, វីដេអូបង្រៀន, សំនួរ, បច្ចេកវិទ្យា" />

    <title><%= full_title yield(:title) %></title>    
    <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
    <%#= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= render "layouts/async_javascript", path: "application" %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <%= csrf_meta_tags %>
    <%= render "layouts/shim" %>
    <%= favicon_link_tag "icon-logo.ico" %>
  </head>
  <body>
    <%= render "layouts/admin/header" %>

    <div class="row admin-head">
      <div class="col-lg-12">
        <% flash.each do |key, value| %>
         <%= content_tag(:div, value, class: "alert alert-#{(key == "danger")? "danger" : "success"}") %>
        <% end %>
        <div class="col-md-12">
          <%= render "shared/locale_lang" %>
        </div>
        <div class="clear_float">
          <%= yield %>
        </div>        
      </div>
    </div>
  </body>
</html>