config/routes.rb
Rails.application.routes.draw do
  devise_for :users, skip: [:session, :registration],
              controllers: { omniauth_callbacks: "omniauth_callbacks" }

  devise_for :users, controllers: {omniauth_callbacks: "omniauth_callbacks",
                                  passwords: "passwords",
                                  sessions: "sessions",
                                  confirmations: "confirmations",
                                  registrations: "registrations"}, skip: [:omniauth_callbacks]
  devise_scope :user do
    get "sign_out", to: "devise/sessions#destroy"
  end
    namespace :admin do
    root "static_pages#dashboard"
    get "about"=> "static_pages#about"
    get "edit_about"=> "static_pages#edit_about"
    patch "update_about"=> "static_pages#update_about"
    resources :videos
    resources :tags
    resources :articles
    resources :users
    resources :activities, only: [:index]
    resources :comments, only: [:show, :index, :destroy]
  end
  resources :tags, only: [:show]
  resources :users, only: [:show] do
    resources :activities, only: :index
    member do
      get "question"
      get "comment"
    end
  end
  resources :searchs, only: [:index]
  resources :articles, only: [:show, :index] do
    resources :comments
  end
  resources :videos, only: [:show, :index] do
    resources :comments
  end
  root "static_pages#home"
  get "about" => "static_pages#about"
  get "privacy" => "static_pages#privacy"

  # get "*path", to: redirect("/#{I18n.default_locale}/%{path}")
  # get "", to: redirect("/#{I18n.default_locale}/")
  match "errors/500", to: "errors#500", via: :all
  match "errors/404", to: "errors#404", via: :all
  match "errors/422", to: "errors#422", via: :all
  match "(errors)/:status", to: "errors#show", constraints: {status: /\d{3}/}, via: :all

  get "*path", to: redirect("/kh/%{path}"),
    constraints: lambda {|req| !req.path.starts_with?("/kh/") && !req.path.starts_with?("/en/")}
  get "", to: redirect("/kh/")
end

app/models/video.rb
class Video < ActiveRecord::Base
  extend FriendlyId
  # enum status: [:show, :hide]
  before_save :default_values
  has_one :snippet, dependent: :destroy
  has_many :comments, as: :commentable, dependent: :destroy
  has_many :video_tags, dependent: :destroy
  has_many :tags, through: :video_tags
  belongs_to :user

  URL_FORMATS = {
      regular: /^(https?:\/\/)?(www\.)?youtube.com\/watch\?(.*\&)?v=(?<id>[^&]+)/,
      shortened: /^(https?:\/\/)?(www\.)?youtu.be\/(?<id>[^&]+)/,
      embed: /^(https?:\/\/)?(www\.)?youtube.com\/embed\/(?<id>[^&]+)/,
      embed_as3: /^(https?:\/\/)?(www\.)?youtube.com\/v\/(?<id>[^?]+)/,
      chromeless_as3: /^(https?:\/\/)?(www\.)?youtube.com\/apiplayer\?video_id=(?<id>[^&]+)/
  }

  INVALID_CHARS = /[^a-zA-Z0-9\:\/\?\=\&\$\-\_\.\+\!\*\'\(\)\,]/
  # YT_LINK_FORMAT = /\A.*(youtu.be\/|v\/|u\/\w\/|embed\/|watch\?v=|\&v=)([^#\&\?]*).*/i
  YT_LINK_FORMAT = /\A(?:https?:\/\/)?(?:www\.)?youtu(?:\.be|be\.com)\/(?:watch\?v=)?([\w-]{10,})/
  validates :file_link, presence: true, format: YT_LINK_FORMAT
  validates :title, :description, presence: true
  validates :duration, numericality: { only_integer: true, greater_than: 0 }
  mount_uploader :image, ImageUploader

  friendly_id :title, use: :slugged
  accepts_nested_attributes_for :snippet, allow_destroy: true

  scope :order_video, ->{
    order("created_at DESC")
  }

  def self.status_show
    where status: true
  end

  def simlar_videos
    if tags.any?
      tags.order("RAND()").first.videos.order("RAND()").limit(4)
    else
      Video.order("RAND()").limit(4)
    end
  end

  def has_invalid_chars?(youtube_url)
    !INVALID_CHARS.match(youtube_url).nil?
  end

  def extract_video_id
    return nil if has_invalid_chars?(file_link)

    URL_FORMATS.values.each do |format_regex|
      match = format_regex.match(file_link)
      return match[:id] if match
    end
  end

  def default_values
    self.status ||= :show
    self.publish_date ||= Date.current
  end
end

app/controllers/admin/videos_controller.rb
class Admin::VideosController < ApplicationController
  before_action :authenticate_user!
  before_action :admin_user
  layout "admin/application"

  def show
    @video = Video.includes(:user, :tags)
                  .friendly.find params[:id]
  end

  def index
    @videos = Video.order(publish_date: :desc).paginate page: params[:page], per_page: 7
  end

  def new
    @video = current_user.videos.new
    @video.build_snippet
  end

  def create
    @video = current_user.videos.new video_params
    if @video.save
      track_activity @video
      flash[:success] = t "flash.success_create"
      redirect_to [:admin, @video]
    else
      flash.now[:danger] = t "flash.fail_create"
      render "new"
    end
  end

  def edit
    @video = Video.friendly.find params[:id]
  end

  def update
    @video = Video.friendly.find params[:id]
    if @video.update_attributes video_params
      flash[:success] = t "flash.success_update"
      track_activity @video
      redirect_to [:admin, @video]
    else
      flash.now[:danger] = t "flash.fail_update"
      render "edit"
    end
  end

  def destroy
    @video = Video.friendly.find params[:id]
    @video.destroy
    track_activity @video
    flash[:success] = t "flash.success_delete"
    redirect_to admin_videos_path
  end

  private
  def video_params
    params.require(:video).permit :id, :title, :image, :image_cache, :description,
                                  :link, :file_link, :duration, :status, :publish_date,
                                  snippet_attributes: [:id, :content], tag_ids:[]

  end

  def admin_user
    redirect_to root_url unless current_user.admin? || current_user.super?
  end
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  def show
    @video = Video.status_show.friendly.find(params[:id])
    @commentable = @video
    @comments = @commentable.comments
    @comment = Comment.new
    @simlar_videos = @video.simlar_videos
  end

  def index
    @videos = Video.status_show.order(publish_date: :desc).paginate page: params[:page], per_page: 7
  end
end

app/views/videos/_video.html.erb
<!-- <div class="row"> -->
  <div class="col-md-12 video-show">
    <div class="col-md-4 screenshot">
      <%= link_to video_path(video) do %>
        <%= image_tag video.image, class: "img-responsive" %>
      <% end %>
    </div>
    <div class="col-md-8 video-info">
      <h2>
        <%= link_to video.title, video_path(video) %>
      </h2>
      <span class="text-muted small">
        <em>
        <%= t("label.post_by") %> <%= (link_to video.user.name, video.user) if video.user %>
        <br/>
        <%= l video.publish_date.localtime.to_date %>
        <%= t("videos.label.duration") %><%= video.duration %> <%= t("videos.label.minute") %>
        , <%= video.comments.size %> <%= t("articles.label.comment") %>
        <br/>
        <%= t("question.label.tags") %>
        <% video.tags.each do |tag| %>
          <%= link_to tag.name, tag %>
        <% end %>
        </em>
      </span>
      <br>
      <p><%= video.description %></p>
      <%= link_to t("videos.link.read_more"), video_path(video) %>
    </div>
  </div>
<!-- </div> -->

app/views/videos/index.html.erb
<% if params[:search].present? %>
  <% provide :title, "#{t("page_title.search_video")} " + params[:search].to_s %>
  <b><%= t("search.label.filter") %> <%= params[:search] %></b>
  <% unless @videos && @videos.any? %>
    <p><%= t("search.label.video_no_found") %>  <%= link_to t("search.link.all_video"), videos_path %></p>
  <% else %>    
    <%= render @videos %>
    <%= will_paginate @videos %>
  <% end %>
<% else %>
  <% provide :title, t("page_title.video") %>
  <%= render @videos %>
  <%= will_paginate @videos %>
<% end %>

app/views/videos/show.html.erb
<% provide :title, @video.title %>
<div class="row">
  <div class="col-md-12 white-container video-detail" id="video-show">
    <div class="embed-responsive embed-responsive-16by9 video_wrapper">
      <iframe class="embed-responsive-item" src="http://www.youtube.com/embed/<%= @video.extract_video_id %>" allowfullscreen>
      </iframe>
    </div>
  </div>  
  <div class="col-md-12 video-info white-container video-detail">
    <h2><%= @video.title %></h2>
    <span class="text-muted small">
      <em>
        <%= t("label.post_by") %> <%= (link_to @video.user.name, @video.user) if @video.user %>
        <br/>
        <%= l @video.publish_date.localtime.to_date %>
        <%= t("videos.label.duration") %><%= @video.duration %> <%= t("videos.label.minute") %>
        <br/>      
        <%= t("videos.label.tags") %>
        <% @video.tags.each do |tag| %>
          <%= link_to tag.name, tag %>
        <% end %>        
      </em>
    </span>
    <br>
    <%= social_share_button_tag(@video.title, image: @video.image, desc: @video.description, popup: "true") %>
    <%= @video.description %>
  </div>  

  <div class="col-md-12 white-container video-detail">
    <div class="panel panel-default">
      <div class="panel-body">
        <div class="row">         
          <div class="col-md-12">
            <%= render @video.snippet %>
          </div>
          <div class="col-md-12">
            <br/>
            <%= render "comments/comments" %>
            <% if user_signed_in? %>
              <div id="reply_comment_form">
                <%= render "comments/form", comment_title: t("videos.label.comment_title") %>  
              </div>
            <% else %>
                <%= link_to t("videos.link.sign_in"), new_user_session_path  %>
                <%= t("videos.label.comment_info") %>
            <% end %>            
          </div>          
        </div>
      </div>      
    </div>
  </div>  
  <div class="well col-md-12 video-detail">    
    <% @simlar_videos.each do |video| %>
      <div class="col-xs-6 col-sm-3 similar-video">
        <%= link_to video do %>
          <%= image_tag video.image, class: "img-responsive" %>
          <p><%= truncate video.description, length: 50 %></p>
        <% end %>
      </div>
    <% end %>
  </div>
</div>
<script src="https://google-code-prettify.googlecode.com/svn/loader/run_prettify.js" data-no-turbolink ></script>