config/routes.rb
Rails.application.routes.draw do
  devise_for :users, skip: [:session, :registration],
              controllers: { omniauth_callbacks: "omniauth_callbacks" }

  devise_for :users, controllers: {omniauth_callbacks: "omniauth_callbacks",
                                  passwords: "passwords",
                                  sessions: "sessions",
                                  confirmations: "confirmations",
                                  registrations: "registrations"}, skip: [:omniauth_callbacks]
  devise_scope :user do
    get "sign_out", to: "devise/sessions#destroy"
  end
    namespace :admin do
    root "static_pages#dashboard"
    get "about"=> "static_pages#about"
    get "edit_about"=> "static_pages#edit_about"
    patch "update_about"=> "static_pages#update_about"
    resources :videos
    resources :tags
    resources :articles
    resources :users
    resources :activities, only: [:index]
    resources :comments, only: [:show, :index, :destroy]
  end
  resources :tags, only: [:show]
  resources :users, only: [:show] do
    resources :activities, only: :index
    member do
      get "question"
      get "comment"
    end
  end
  resources :searchs, only: [:index]
  resources :articles, only: [:show, :index] do
    resources :comments
  end
  resources :videos, only: [:show, :index] do
    resources :comments
  end
  root "static_pages#home"
  get "about" => "static_pages#about"
  get "privacy" => "static_pages#privacy"

  # get "*path", to: redirect("/#{I18n.default_locale}/%{path}")
  # get "", to: redirect("/#{I18n.default_locale}/")
  match "errors/500", to: "errors#500", via: :all
  match "errors/404", to: "errors#404", via: :all
  match "errors/422", to: "errors#422", via: :all
  match "(errors)/:status", to: "errors#show", constraints: {status: /\d{3}/}, via: :all

  get "*path", to: redirect("/kh/%{path}"),
    constraints: lambda {|req| !req.path.starts_with?("/kh/") && !req.path.starts_with?("/en/")}
  get "", to: redirect("/kh/")
end

app/models/video.rb
class Video < ActiveRecord::Base
  extend FriendlyId
  # enum status: [:show, :hide]
  before_save :default_values
  has_one :snippet, dependent: :destroy
  has_many :comments, as: :commentable, dependent: :destroy
  has_many :video_tags, dependent: :destroy
  has_many :tags, through: :video_tags
  belongs_to :user

  URL_FORMATS = {
      regular: /^(https?:\/\/)?(www\.)?youtube.com\/watch\?(.*\&)?v=(?<id>[^&]+)/,
      shortened: /^(https?:\/\/)?(www\.)?youtu.be\/(?<id>[^&]+)/,
      embed: /^(https?:\/\/)?(www\.)?youtube.com\/embed\/(?<id>[^&]+)/,
      embed_as3: /^(https?:\/\/)?(www\.)?youtube.com\/v\/(?<id>[^?]+)/,
      chromeless_as3: /^(https?:\/\/)?(www\.)?youtube.com\/apiplayer\?video_id=(?<id>[^&]+)/
  }

  INVALID_CHARS = /[^a-zA-Z0-9\:\/\?\=\&\$\-\_\.\+\!\*\'\(\)\,]/
  # YT_LINK_FORMAT = /\A.*(youtu.be\/|v\/|u\/\w\/|embed\/|watch\?v=|\&v=)([^#\&\?]*).*/i
  YT_LINK_FORMAT = /\A(?:https?:\/\/)?(?:www\.)?youtu(?:\.be|be\.com)\/(?:watch\?v=)?([\w-]{10,})/
  validates :file_link, presence: true, format: YT_LINK_FORMAT
  validates :title, :description, presence: true
  validates :duration, numericality: { only_integer: true, greater_than: 0 }
  mount_uploader :image, ImageUploader

  friendly_id :title, use: :slugged
  accepts_nested_attributes_for :snippet, allow_destroy: true

  scope :order_video, ->{
    order("created_at DESC")
  }

  def self.status_show
    where status: true
  end

  def simlar_videos
    if tags.any?
      tags.order("RAND()").first.videos.order("RAND()").limit(4)
    else
      Video.order("RAND()").limit(4)
    end
  end

  def has_invalid_chars?(youtube_url)
    !INVALID_CHARS.match(youtube_url).nil?
  end

  def extract_video_id
    return nil if has_invalid_chars?(file_link)

    URL_FORMATS.values.each do |format_regex|
      match = format_regex.match(file_link)
      return match[:id] if match
    end
  end

  def default_values
    self.status ||= :show
    self.publish_date ||= Date.current
  end
end

app/controllers/admin/videos_controller.rb
class Admin::VideosController < ApplicationController
  before_action :authenticate_user!
  before_action :admin_user
  layout "admin/application"

  def show
    @video = Video.includes(:user, :tags)
                  .friendly.find params[:id]
  end

  def index
    @videos = Video.order(publish_date: :desc).paginate page: params[:page], per_page: 7
  end

  def new
    @video = current_user.videos.new
    @video.build_snippet
  end

  def create
    @video = current_user.videos.new video_params
    if @video.save
      track_activity @video
      flash[:success] = t "flash.success_create"
      redirect_to [:admin, @video]
    else
      flash.now[:danger] = t "flash.fail_create"
      render "new"
    end
  end

  def edit
    @video = Video.friendly.find params[:id]
  end

  def update
    @video = Video.friendly.find params[:id]
    if @video.update_attributes video_params
      flash[:success] = t "flash.success_update"
      track_activity @video
      redirect_to [:admin, @video]
    else
      flash.now[:danger] = t "flash.fail_update"
      render "edit"
    end
  end

  def destroy
    @video = Video.friendly.find params[:id]
    @video.destroy
    track_activity @video
    flash[:success] = t "flash.success_delete"
    redirect_to admin_videos_path
  end

  private
  def video_params
    params.require(:video).permit :id, :title, :image, :image_cache, :description,
                                  :link, :file_link, :duration, :status, :publish_date,
                                  snippet_attributes: [:id, :content], tag_ids:[]

  end

  def admin_user
    redirect_to root_url unless current_user.admin? || current_user.super?
  end
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  def show
    @video = Video.status_show.friendly.find(params[:id])
    @commentable = @video
    @comments = @commentable.comments
    @comment = Comment.new
    @simlar_videos = @video.simlar_videos
  end

  def index
    @videos = Video.status_show.order(publish_date: :desc).paginate page: params[:page], per_page: 7
  end
end

app/views/admin/videos/_form.html.erb
<%= form_for [:admin, @video], validate: true do |f| %>

  <%= render "shared/error_message", object: f.object %>
  <div class="row">
    <div class="col-md-8 col-md-offset-2">

      <center>
        <%= image_tag f.object.image, class:"img-round img-responsive user_profile", id: "uploadPreview"  %>
      </center>
      
      <div class="form-group">
        <%= f.label :image, t("admin.videos.label.screenshot") %>
        <%= f.file_field :image, class: "form-control", id: "uploadImage", onchange:"PreviewImage();", accept: "image/png,image/gif,image/jpeg" %>
        <%= f.hidden_field :image_cache %>
      </div>
      
      <div class="form-group">        
        <%= f.text_field :file_link, class: "form-control", placeholder: Video.human_attribute_name(:file_link), autofocus: true %>
      </div>

      <div class="form-group">
        <%= f.label t("admin.articles.label.tag") %>
        <%= f.collection_select :tag_ids, Tag.with_translations.order(:name), "id", "name",{},{multiple: true, size: 5, class: "form-control tags_choosen"} %>        
      </div>
      
      <div class="form-group">        
        <%= f.text_field :title, class: "form-control", placeholder: Video.human_attribute_name(:title) %>
      </div>
      
      <div class="form-group">
        <%= f.label :publish_date %>
        <div class="form-inline">
          <%= f.date_select :publish_date, {start_year: Time.now.year, end_year: 5.year.ago.year,
            order: [:day, :month, :year], validate: false,
            prompt: { day: t("label.day"), month: t("label.month"), year: t("label.year") }},
            {class: "form-control selectwidthauto"} %>
        </div>
      </div> 
      <div class="form-group">        
        <%= f.text_area :description, rows:5, class: "form-control", placeholder: Video.human_attribute_name(:description) %>
      </div>

      <div class="form-group">        
        <%= f.number_field :duration, class: "form-control", placeholder: Video.human_attribute_name(:duration) %>
      </div>        
    </div>      
  </div>
  <div class="form-group">
    <%= t("comments.label.use_markdown") %>
    <a href="javascript:void(0)" class="markdown_link"><%= t("comments.label.here") %></a>
    <div class="markdown_examples">
      <%= render "shared/markdown_sample" %>
    </div>
    <br/>
    <%= f.fields_for :snippet do |builder| %>      
      <%= builder.text_area :content, rows: 25, class: "form-control", placeholder: Snippet.human_attribute_name(:content) %>
    <% end %>
  </div>
  <div class="form-group">
    <%= f.label :status, class: "radio-inline", value: true do %>
      <%= f.radio_button :status, true %><%= t("admin.videos.label.show") %>
    <% end%>
    <%= f.label :status, class: "radio-inline", value: false do %>
      <%= f.radio_button :status, false %><%= t("admin.videos.label.hide") %>
    <% end%>
  </div>  
  <div class="actions">
    <%= f.button :submit, class: "btn btn-primary" do %>
      <i class="fa fa-floppy-o"> </i> <%= action %>
    <% end %>        
  </div>
<% end %>
<script type="text/javascript">
  $(".markdown_examples").hide();
  $(".markdown_link").click(function(){
    if($(".markdown_examples").is(":visible")){
      $(".markdown_examples").hide();
    }else{
      $(".markdown_examples").show();
    }    
  });
</script>

app/views/admin/videos/_video.html.erb
<tr>
  <td>
    <p><%= link_to (truncate video.title, length: 20), admin_video_path(video) %></p>
  </td>
  <td>
    <p><%= link_to (truncate video.description, length: 20), admin_video_path(video) %></p>
  </td>
  <td>
    <%= (link_to video.user.name, video.user) if video.user %>
  </td>
  <td>
    <%= video.duration %>
  </td>
  <td>
    <%= video.status  ? t("admin.videos.label.show") : t("admin.videos.label.hide") %>
  </td>
  <td>
    <%= link_to t("link.detail"), admin_video_path(video) %>
    | <%= link_to t("link.edit"), edit_admin_video_path(video) %>
    | <%= link_to t("link.delete"), admin_video_path(video), data: {method: :delete, confirm: t("info.confirm_delete")} %>
  </td>
</tr>

app/views/admin/videos/edit.html.erb
<div class="row">
  <div class="col-md-10 col-md-offset-1 well">
    <%= link_to :back do %>
      <i class="fa fa-arrow-left"></i> <%= t("link.back") %>
    <% end %>
    <u><h4 class="center"><%= t("admin.videos.label.edit_video") %></h4></u>
    <%= render "form", action: t("action.update") %>
  </div>
</div>

app/views/admin/videos/index.html.erb
<div class="col-md-12 well">  
  <legend><h3><%= t("admin.videos.label.video") %></h3>
    <div class="col-md-3 pull-right">
      <%= form_tag(admin_videos_path, :method => "get", class: "", id: "search-form", role: "search") do %>
      <div class="input-group">
        <%= text_field_tag :search, params[:search], class: "form-control", placeholder: t("admin.videos.label.search") %>
           <div class="input-group-btn">
              <button type="submit" class="btn btn-default">
                 <i class="fa fa-search fa-lg"></i>
              </button>
           </div>            
      </div>
    <% end %>
    </div>
  </legend>
  <%= link_to t("admin.videos.link.new_video"), new_admin_video_path %>
  <table class="table">
    <thead>
      <th><%= t("admin.videos.label.title") %></th>
      <th><%= t("admin.videos.label.description") %></th>
      <th><%= t("admin.videos.label.author") %></th>
      <th><%= t("admin.videos.label.duration") %></th>
      <th><%= t("admin.videos.label.status") %></th>
      <th><%= t("admin.videos.label.action") %></th>
    </thead>
    <tbody>
      <%= render @videos %>    
    </tbody>
  </table>
  <%= will_paginate @videos %>
</div>

app/views/admin/videos/new.html.erb
<div class="row">
  <div class="col-md-10 col-md-offset-1 well">
    <%= link_to :back do %>
      <i class="fa fa-arrow-left"></i> <%= t("link.back") %>
    <% end %>
    <h4 class="center"><%= t("admin.videos.label.new_video") %></h4>
    <%= render "form", action: t("action.create") %>
  </div>
</div>

app/views/admin/videos/show.html.erb
<div class="row" id="video-show">  
  <div class="col-md-10 col-md-offset-1">
    <div class="embed-responsive embed-responsive-16by9 video_wrapper">
      <iframe class="embed-responsive-item" src="http://www.youtube.com/embed/<%= @video.extract_video_id %>" allowfullscreen>
      </iframe>
    </div>    
  </div>

  <div class="col-md-3 screenshot">
    <%= image_tag @video.image, class: "img-responsive" %>
    <%= link_to edit_admin_video_path(@video), class: "btn btn-primary btn-read-video" do %>
      <i class="fa fa-pencil-square-o"> </i> <%= t("link.edit") %>
    <% end %>
    <%= link_to admin_video_path(@video), data: {method: :delete, confirm: t("info.confirm_delete")} , class: "btn btn-danger btn-read-video" do %>
      <i class="fa fa-trash-o"></i> <%= t("link.delete") %>
    <% end %>
  </div>  
  <div class="col-md-8 video-info">
    <h2 class="comment-text"><%= @video.title %></h2>
    <span class="info">
      <%= t("admin.videos.label.author") %> <%= (link_to @video.user.name, @video.user) if @video.user %><br/>
      <%= l @video.publish_date.to_date %>
      <%= t("admin.videos.label.duration") %><%= @video.duration %> <%= t("admin.videos.label.minute") %>
      <br/>      
        <%= t("admin.videos.label.tag") %>
        <% @video.tags.each do |tag| %>
          <%= link_to tag.name, [:admin, tag] %>,
        <% end %>
      <br/>
      <%= t("admin.videos.label.video_link") %> <%= link_to @video.file_link, @video.file_link, target: "_blank" %>
      <br/>
      <%= t("admin.videos.label.status") %>: <%= @video.status  ? t("admin.videos.label.show") : t("admin.videos.label.hide") %>
    </span>
    <br>
    <p><%= @video.description %></p>    
  </div>  
</div>
<div class="row">
  <div class="col-md-12">
    <div class="panel panel-default">
      <div class="panel-body">
        <div class="row">
          <div class="col-md-12">
            <% if @video.snippet %>
              <%= render "snippets/snippet", snippet: @video.snippet %>
            <% end %>
          </div>
          <div class="col-md-12">
            <%= t("admin.videos.label.total_comment") %>
          </div>          
        </div>
      </div>      
    </div>
  </div>
</div>
<script src="https://google-code-prettify.googlecode.com/svn/loader/run_prettify.js" data-no-turbolink ></script>